image:
  file: Dockerfile
ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - init: composer install,
          git clone https://github.com/constantinjoly/512 themes/512
  - name: Unix
    command: >
          cp -r themes/512/. public
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log